import { StyleSheet } from "react-native";
import { normalize } from "../../../../assets/normalize";

const n = (value: number) => normalize(value / 3.5);

const styles = StyleSheet.create({
overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.18)",
    justifyContent: "center",
    alignItems: "center",
},
popup: {
    width: n(320),
    backgroundColor: "#FFD2B3",
    borderRadius: n(18),
    borderWidth: n(5),
    borderColor: "#7A6B63",
    alignItems: "center",
    paddingVertical: n(28),
    paddingHorizontal: n(18),
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: n(12),
    elevation: 10,
},
message: {
    fontSize: n(22),
    color: "#7A6B63",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: n(22),
    textShadowColor: "#fff",
    textShadowOffset: { width: n(1), height: n(1) },
    textShadowRadius: n(1),
    fontFamily: "sans-serif",
},
buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    gap: n(12),
},
buttonSingle: {
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
},
confirmButton: {
    flex: 1,
    backgroundColor: "#4DD16E",
    borderRadius: n(12),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: n(4),
    borderColor: "#2B8C3E",
    height: n(48),
    marginHorizontal: n(2),
    shadowColor: "#2B8C3E",
    shadowOpacity: 0.18,
    shadowRadius: n(6),
    elevation: 4,
    minWidth: n(100),
    paddingHorizontal: n(10),
},
confirmButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: n(22),
    letterSpacing: 1,
    textShadowColor: "#7A6B63",
    textShadowOffset: { width: n(2), height: n(2) },
    textShadowRadius: n(1),
},
cancelButton: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: n(12),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: n(4),
    borderColor: "#7A6B63",
    height: n(48),
    marginHorizontal: n(2),
    minWidth: n(100),
    paddingHorizontal: n(10),
},
cancelButtonText: {
    color: "#7A6B63",
    fontWeight: "bold",
    fontSize: n(22),
    letterSpacing: 1,
    textShadowColor: "#fff",
    textShadowOffset: { width: n(1), height: n(1) },
    textShadowRadius: n(1),
},
});

export default styles;